[package]
name = "text-block"
version = "0.1.2"
authors = ["Louis Birla <louis.birla@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
block-tools = { path = "../../block-tools" }
data-block = { path = "../data-block" }
serde_json = "1.0"
serde = "1"
